### PR TITLE
Create README.md for WSA Documentation

### PR DESCRIPTION
**Pull request by MustardChef**

### CODE REVIEW

**Comment by skalwaghe-56** [comment]
> _ No description provided. _

I would like to pull request for translation purpose would like to contribute!

**Comment by MustardChef** [comment]
> > _ No description provided. _
> 
> I would like to pull request for translation purpose would like to contribute!

Sure. That would be great help. I am currently setting up a new repo for the Documentation. Will post the link to the repo, when it is fully set-up.

**Comment by skalwaghe-56** [comment]
Ok so how can I pull a request I am new but want to contribute

**Comment by skalwaghe-56** [comment]
Please tell me how to pull a request and what to do to help in the translation you can mail me on skalwaghe56@gmail.com to give the steps also please provide me access so I can contribute

**Comment by MustardChef** [comment]
Well. I am planning on using Weblate or Crowdin for easy localisation/translation. So it will be easier than having pull requests.

**Comment by skalwaghe-56** [comment]
So I cannot help you okay if you need any help just ping me!

**Comment by MustardChef** [comment]
> Hi Tell me if I can help in any way!

I will. I have still a lot of work to do on the Documentation, so it will be in a few weeks time.

**Comment by Snowlights2022** [comment]
I am Chinese, feeling excited about the plan from @MustardChef . It is August now, I don't know if the foundation of translation was done or not. I have subscribed this PR in order to get the latest progress. 
If the translation for **zh-cn** or **zh-hans** is still not finished, could you give me a link or other method about it at convenience? In this way, I can make a contribution easier for this useful project!
**Thx!**

**Comment by MustardChef** [comment]
@Snowlights2022 
Hello, Thank you for your interest. 

I have completed the documentation. But, quite frankly, I have been busy with a few things and so I have not been able to make good of my promise of releasing it "in a few weeks time." I apologise for this.

Once I have setup the GitHub Repo and a localization platform, I will post a link here.

Many thanks,
MustardChef

**Pull request closed without merging**
